var songlist_ar = 
[
'Bokura no LIVE Kimi to no LIFE',
'Yuujou No Change',
'Snow halation',
'Baby maybe Koi no Button',
'Natsuiro Egao de 1,2,Jump!',
'Mermaid festa vol.1',
'Mogyutto "love" de Sekkin Chuu!',
'Aishiteru Banzai',
'Wonderful Rush',
'Oh, Love & Peace!',
'Bokura wa Ima no Naka de',
'WILD STARS',
'Kitto Seishun ga Kikoeru',
'Kaguya no Shiro de Odoritai',
'Susume Tomorrow',
'START:DASH!!',
'Korekara no Someda',
'Wonder zone',
'No brand girls',
'START:DASH!!',
'Music S.T.A.R.T!!',
'LOVELESS WORLD',
'Takaramonozu',
'Paradise Live',
'Sore wa Bokutachi no Kiseki',
'Datte Datte Aa Mujou',
'Donna Toki mo Zutto',
'COLORFUL VOICE',
'Yume no Tobira',
'SENTIMENTAL Steps',
'Love wing bell',
'Dancing stars on me!',
'KiRa-KiRa Sensation!',
'Happy Maker!',
'Shangri-La Shower',
'Ruteshi Kisuki Shiteru',
'Mi wa Music no Mi',
'Super LOVE = Super LIVE!',
'Angelic Angel',
'Hello, Hoshi o Kazoete',
'SUNNY DAY SONG',
'HEARTBEAT',
'Bokutachi wa Hitotsu no Hikari',
'Future style',
'HEART to HEART!',
'Arashi no Naka no Koi dakara',
'MOMENT RING',
'Sayounara e Sayonara!',
]
