var numOfSongsMuseAll = 48;
var muse_together_ar = 
[
'Bokura no LIVE Kimi to no LIFE',
'Yuujou No Change',
'Snow halation',
'Baby maybe Koi no Button',
'Natsuiro Egao de 1,2,Jump!',
'Mermaid festa vol.1',
'Mogyutto "love" de Sekkin Chuu!',
'Aishiteru Banzai',
'Wonderful Rush',
'Oh, Love & Peace!',
'Bokura wa Ima no Naka de',
'WILD STARS',
'Kitto Seishun ga Kikoeru',
'Kaguya no Shiro de Odoritai',
'Susume Tomorrow',
'START:DASH!!',
'Korekara no Someda',
'Wonder zone',
'No brand girls',
'START:DASH!!',
'Music S.T.A.R.T!!',
'LOVELESS WORLD',
'Takaramonozu',
'Paradise Live',
'Sore wa Bokutachi no Kiseki',
'Datte Datte Aa Mujou',
'Donna Toki mo Zutto',
'COLORFUL VOICE',
'Yume no Tobira',
'SENTIMENTAL Steps',
'Love wing bell',
'Dancing stars on me!',
'KiRa-KiRa Sensation!',
'Happy Maker!',
'Shangri-La Shower',
'Ruteshi Kisuki Shiteru',
'Mi wa Music no Mi',
'Super LOVE = Super LIVE!',
'Angelic Angel',
'Hello, Hoshi o Kazoete',
'SUNNY DAY SONG',
'HEARTBEAT',
'Bokutachi wa Hitotsu no Hikari',
'Future style',
'HEART to HEART!',
'Arashi no Naka no Koi dakara',
'MOMENT RING',
'Sayounara e Sayonara!'
];

var numOfSongsMuseSub = 31;
var muse_subgroup_ar = 
[
'Love marginal',
'Sweet & Sweet Holiday',
'Pure girls project',
'UNBALANCED LOVE',
'Puwa Puwa-O!',
'Eien Friends',
'Nightingale Love Song',
'CheerDay CheerGirl!',
'MUSEUM de Dou Shitai?',
'WAO-WAO Powerful day!',
'NO EXIT ORION',
'Diamond Princess no Yuuutsu',
'Love Novels',
'Cutie Panther',
'Natsu, Owaranai de.',
'Fuyu ga Kureta Yokan',
'Trouble Busters',
'Silent tonight',
'Saitei de Saikou no Paradiso',
'Sakkaku CROSSROADS',
'PSYCHIC FIRE',
'Shiranai Love Oshiete Love',
'A-NO-NE-GA-N-BA-RE!',
'Binetsu Kara Mystery',
'Kimi no Kuse ni!',
'Aki no Anata no Sora Tooku',
'Futari Happiness',
'Onaji Hoshi ga Mitai',
'Otohime Heart de Love Kyuuden',
'Omoide Ijou ni Naritakute',
'Shunjou Romantic'
];

var numOfSongsMuseOther = 46;
var muse_individual_ar =
[
'Mermaid festa vol.2 Passionate',
'Someday of my life',
'Koi no Signal Rin rin rin!',
'Kokuhaku Biyori, desu!',
'Blueberry Train',
'Kodoku na Heaven',
'Otome Shiki Renai Juku',
'Mahoutsukai Hajimemashita!',
'Junai Lens',
'Soldier Game',
'Daring!!',
'Yuuki no Reason',
'Arifureta Kanashimi no Hate',
'Ai wa Taiyou Ja Nai?',
'Mou Hitori Ja Nai yo',
'Watashitachi wa Mirai no Hana',
'Spicaterrible',
'Listen to my heart!!',
'After School NAVIGATORS',
'Yume Naki Yume wa Yume ja nai',
'Anemone Heart',
'Nawatobi',
'Beat in Angel',
'Niko puri Joshi dou',
'Garasu No Hanazono',
'LONELIEST BABY',
'Shiawase Iki No SMILING!',
'Zurui Yo Magnetic Today',
'Kururin MIRACLE',
'Storm in Lover',
'Moshimo Kara Kitto',
'Suki desu ga Suki desu ka?',
'Soshite Saigo No Page Ni Wa',
'Korekara',
'ENDLESS PARADE',
'Dreamin Go! Go!!',
'Kakumei desu ne? Kamisama!',
'Hane wa Shitte Shimatta no?',
'Senkou Resolution',
'Kaku Mo Yuubi Na Hi To Narite',
'I will smile for yours',
'Kodoku No Kairou',
'Himitsu To Hanazono',
'Koko De Matteru Yo',
'Yume ONCE AGAIN',
'NEURON,NEURON!!'
];

var numOfSongsAqoursTogether = 8;
var aqours_together = 
[
'Kimi no Kokoro wa Kagayaiteru Kai?',
'Step! ZERO to ONE',
'Aqours HEROES',
'Aozora Jumping Heart',
'Koi Ni Naritai AQUARIUM',
'Humming Friend',
'Mattete Ai no Uta',
'Todokanai Hoshi da to Shitemo'
];

var numOfSongsAqoursSub = 6;
var aqours_subgroup_ar = 
[
'Strawberry Trapper',
'Guilty Night, Guilty Kiss!',
'Genki Zenkai DAY! DAY! DAY!',
'Yozora wa Nandemo Shitteru no?',
'Tokimeki Bunruigaku',
'Torikoriko PLEASE',
];

var numOfSongsAqoursOthers = 2;
var aqours_others_ar = 
[
'Daisuki dattara Daijoubu!',
'Kimeta yo Hand in Hand',
];
