var storyAr = 
[
['28', 'https://www.youtube.com/embed/-KNyYK4n60k', 'Speaking of Summer...'],
['29', 'https://www.youtube.com/embed/omNbdaPgpdM', 'Speaking of Summer...'],
['30', 'https://www.youtube.com/embed/wk5EJtmO51s', 'Speaking of Summer...'],
['31', 'https://www.youtube.com/embed/85mbXy0e7EE', 'Speaking of Summer...'],
['32', 'https://www.youtube.com/embed/85mbXy0e7EE', 'Speaking of Summer...'],
['33', 'https://www.youtube.com/embed/jRXKMzu8_4I', 'Speaking of Summer...'],
['34', 'https://www.youtube.com/embed/vDj697_MkKM', 'Speaking of Summer...'],
['35', 'https://www.youtube.com/embed/AI1zBJhol9Q', 'Speaking of Summer...'],
['36', 'https://www.youtube.com/embed/WNQaLyU8glE', 'Speaking of Summer...'],
['37', 'https://www.youtube.com/embed/4yG2sVGzF-A', 'If I Knew Magic...'],
['38', 'https://www.youtube.com/embed/NKpCNtqcSxE', 'If I Knew Magic...'],
['39', 'https://www.youtube.com/embed/TcdDq5RdEAk', 'If I Knew Magic...'],
['40', 'https://www.youtube.com/embed/0y4rGoHMFY8', 'If I Knew Magic...'],
['41', 'https://www.youtube.com/embed/F1chXJ_piao', 'If I Knew Magic...'],
['42', 'https://www.youtube.com/embed/7i7pyImLgTo', 'If I Knew Magic...'],
['43', 'https://www.youtube.com/embed/7i7pyImLgTo', 'If I Knew Magic...'],
['44', 'https://www.youtube.com/embed/N-Gnt4zFrhQ', 'If I Knew Magic...'],
['45', 'https://www.youtube.com/embed/ZGOBzwRqIRU', 'If I Knew Magic...'],
['46', 'https://www.youtube.com/embed/bwYxp3w7brU', 'A Place To Go'],
['47', 'https://www.youtube.com/embed/eD8AhQL4Vjo', 'A Place To Go'],
['48', 'https://www.youtube.com/embed/Ft43pDyacY0', 'A Place To Go'],
['49', 'https://www.youtube.com/embed/al7E-HRKncQ', 'A Place To Go'],
['50', 'https://www.youtube.com/embed/yQd16PYUecw', 'A Place To Go'],
['51', 'https://www.youtube.com/embed/ZW5a4Sxg-G8', 'A Place To Go'],
['52', 'https://www.youtube.com/embed/uJHLpb7nkxk', 'A Place To Go'],
['53', 'https://www.youtube.com/embed/5ijlOm4QCyE', 'A Place To Go'],
['54', 'https://www.youtube.com/embed/E_Ruy-rdJCQ', 'A Place To Go'],
['55', 'https://www.youtube.com/embed/xf_HsxwzzGE', 'School Idol Dream'],
['56', 'https://www.youtube.com/embed/wYTeRTYSMdI', 'Victory Goddess'],
['57', 'https://www.youtube.com/embed/geH95F79u5c', 'Your Nurse'],
['58', 'https://www.youtube.com/embed/-yo3964jsF4', 'School Protector'],
['59', 'https://www.youtube.com/embed/z3GstmEQfd0', 'Aiming for a Heart'],
['60', 'https://www.youtube.com/embed/9pzOZLUV_lo', 'Dress-Up'],
['61', 'https://www.youtube.com/embed/XWxxFnC7ZE4', 'Lucky Power'],
['62', 'https://www.youtube.com/embed/4CW0yDzRW18', "I'm Embarrassed..."],
['63', 'https://www.youtube.com/embed/pBZX0DatBwU', "That's the Setting?"],
['64', 'https://www.youtube.com/embed/1MIYMPB8_CE', 'Inspirational Girl'],
['65', 'https://www.youtube.com/embed/HUkEOBPNUwY', 'With Bean Jam!'],
['66', 'https://www.youtube.com/embed/IgfJe4xDbns', 'Super-Popular Nico'],
['71', 'https://www.youtube.com/embed/Wkn5FEm8-ZU', 'Firefighter'],
['72', 'https://www.youtube.com/embed/sAEFA8KurTg', 'Always on the Mark!'],
['73', 'https://www.youtube.com/embed/JlaiAx69MOE', 'Cupid of Love'],
['75', 'https://www.youtube.com/embed/ZaUb9zB97TE', 'Sheepish Kotori'],
['77', 'https://www.youtube.com/embed/a0J_AuKJYQg', "Maki's Exam Room"],
['78', 'https://www.youtube.com/embed/OftuRC-K3Rw ', 'Clumsy Hanayo'],
['79', 'https://www.youtube.com/embed/_IOs8u1ZOaY', 'Super Idol'],
['81', 'https://www.youtube.com/embed/ofg2KMs3N4c', "A Rabbit's Feelings"],
['86', 'https://www.youtube.com/embed/-QR-VPZTZQE', 'School Protector'],
['87', 'https://www.youtube.com/embed/ER2Fjgyaeyg', 'Your Guide'],
['88', 'https://www.youtube.com/embed/Ixs_SMgkHNI', 'An Angel!'],
['90', 'https://www.youtube.com/embed/m-79vjLZTiI', 'Most Popular One'],
['92', 'https://www.youtube.com/embed/ZdI0PARdMHk', 'Sweet Kotori'],
['93', 'https://www.youtube.com/embed/-xpQ5t4pygA', 'Speaking of Rin..'],
['94', 'https://www.youtube.com/embed/CTLU0pw_-Lk', 'Mystery Thief Elichika'],
['99', 'https://www.youtube.com/embed/FzbfF7vtWKs', 'Any Costume'],
['100', 'https://www.youtube.com/embed/uTmbNJYar7w', 'Just Understand it!'],
['101', 'https://www.youtube.com/embed/6ZAY8rvFoxU', 'The Destined One'],
['103', 'https://www.youtube.com/embed/gadMwFx4mKY', 'Tell Me How You Feel'],
['104', 'https://www.youtube.com/embed/GhCJZ4rjpKE', 'Lucky Charm'],
['105', 'https://www.youtube.com/embed/AUqgDwk2Hfw', "Rin's Ramen"],
['107', 'https://www.youtube.com/embed/iit9IMtWFFg', 'The Forest Bear'],
['122', 'https://www.youtube.com/embed/-lJhe5KgIHY', 'Summer Love Action!'],
['123', 'https://www.youtube.com/embed/dFnxuHPpi7U', 'Not Enough Sleep'],
['124', 'https://www.youtube.com/embed/uOXZGfqgyZA', 'Summer Vow'],
['125', 'https://www.youtube.com/embed/Sws3Izm7blY', 'Elephant Sprinkler'],
['126', 'https://www.youtube.com/embed/CsoHKXYBHfU', 'Everyone on Stage'],
['127', 'https://www.youtube.com/embed/h-9V_t5pyU8', 'Private Summer'],
['129', 'https://www.youtube.com/embed/50bcRVJiBCA', 'Fluffy Tail'],
['131', 'https://www.youtube.com/embed/q2sj6kWZPdI', 'Kotori and the Pool'],
['132', 'https://www.youtube.com/embed/6d2CtD-Fbxw', "I'm Yours"],
['133', 'https://www.youtube.com/embed/U6pk28EPJdU', 'Being Prepared!'],
['134', 'https://www.youtube.com/embed/KqXJy1UiN_k', 'Cute Bikini Girls'],
['136', 'https://www.youtube.com/embed/lfjXR2rfn-Q', 'Strange Feeling'],
['141', 'https://www.youtube.com/embed/05-LozS5yRg', 'I Love Summer'],
['142', 'https://www.youtube.com/embed/2ccoAmeqOyc', 'No, Not That'],
['143', 'https://www.youtube.com/embed/SFbHlfj5ijc', 'The Lost Voice'],
['144', 'https://www.youtube.com/embed/p5Kz1bRYDMU', 'Summer Miracle'],
['145', 'https://www.youtube.com/embed/v7dCn0skAf4', 'Shared Feelings'],
['150', 'https://www.youtube.com/embed/yphcTLq6pQ8', 'Touchy Spirits'],
['152', 'https://www.youtube.com/embed/eicBMS2YYew', 'Be More Forceful ♪'],
['153', 'https://www.youtube.com/embed/eDbWRx_QWeg', 'Summerfest Appeal'],
['154', 'https://www.youtube.com/embed/uRECSkg2QXM', 'Grown-Up Stairway'],
['155', 'https://www.youtube.com/embed/g3cThtohPbU', 'Tell Me, Tell Me!'],
['157', 'https://www.youtube.com/embed/zw5Dap4ItYY', 'Dumpling Party'],
['161', 'https://www.youtube.com/embed/3bQ0MHqtoIg', 'Race for Love'],
['162', 'https://www.youtube.com/embed/kqhZMkcYpMo', 'Beloved Sports Idol'],
['163', 'https://www.youtube.com/embed/Iyq80LyZq5M', 'Cheering for Us'],
['164', 'https://www.youtube.com/embed/XVKkdh4seSE', "I'm Getting Nervous"],
['165', 'https://www.youtube.com/embed/0dlq-D0KiV8', 'Take on the Challenge!'],
['167', 'https://www.youtube.com/embed/i6FAiNZsWB4', 'Master of the House'],
['169', 'https://www.youtube.com/embed/jYYxMlsCca8', 'Worry and Stress!'],
['170', 'https://www.youtube.com/embed/ygfBzIiXdFc', "You're So Tricky!"],
['171', 'https://www.youtube.com/embed/SA9GFW6XA-Q', 'No Credit'],
['172', 'https://www.youtube.com/embed/qKJVBUgN6I4', 'Scavenger Hunt'],
['174', 'https://www.youtube.com/embed/mrd9Db0V5Ng', 'Secrets from the Book'],
['176', 'https://www.youtube.com/embed/XxQTPQ7PhCE', 'Special Dish'],
['177', 'https://www.youtube.com/embed/CUj0hz2hdrw', "Elichika's Special"],
['178', 'https://www.youtube.com/embed/5P_cy2Ow8Lw', 'Simmering Stew'],
['179', 'https://www.youtube.com/embed/g3ZZJB2A_hU', 'Homely Smile'],
['180', 'https://www.youtube.com/embed/75q8Dlq5Ti0', 'Hibernation'],
['182', 'https://www.youtube.com/embed/l_Aq-BGAPuU', 'Lucky Charm'],
['184', 'https://www.youtube.com/embed/o01w7eaKWZE', 'Full of Nutrition'],
['185', 'https://www.youtube.com/embed/ZWdmDFjpXKM', 'My Special Ramen'],
['186', 'https://www.youtube.com/embed/odm2fAJhKKQ', 'Quick Recipe'],
['187', 'https://www.youtube.com/embed/2x8LSpFHrbY', 'Ordinary Lunch'],
['189', 'https://www.youtube.com/embed/x7Z9q0UA254', 'Tingly Heart'],
['192', 'https://www.youtube.com/embed/cI-0BKrb__Q', 'Miraculous Night'],
['193', 'https://www.youtube.com/embed/SeP3PodMLJc', 'No Food No Problem'],
['194', 'https://www.youtube.com/embed/O4DqEj2zghw', 'Christmas Memories'],
['195', 'https://www.youtube.com/embed/9uMRNtE2f6k', 'True Art'],
['196', 'https://www.youtube.com/embed/03CdCFsMJEQ', 'Were You Being Good?'],
['198', 'https://www.youtube.com/embed/q-9RWqmNHyg', 'Skating Together'],
['200', 'https://www.youtube.com/embed/oT4-AGZ15Ag', 'Christmas??'],
['201', 'https://www.youtube.com/embed/j81t5U2gQjs', 'Santa Kotori'],
['202', 'https://www.youtube.com/embed/dqzgvVT0xCg', 'The Magical Lunchbox'],
['203', 'https://www.youtube.com/embed/j1q0S7jEkgg', 'A Gift from My Heart'],
['204', 'https://www.youtube.com/embed/HfzAnbFKGjo', 'Snowman, Kotori Style'],
['206', 'https://www.youtube.com/embed/7l27COnX088', 'A Special Somebody'],
['207', 'https://www.youtube.com/embed/4Wygue1z5oo', 'Can I be your Present?'],
['210', 'https://www.youtube.com/embed/XXMiZcJu2Aw', 'My Source of Happiness'],
['211', 'https://www.youtube.com/embed/6Z_rDn2ExbA', 'Give Me a Good Fortune'],
['212', 'https://www.youtube.com/embed/UEW21jC2gko', 'New Year Greetings'],
['213', 'https://www.youtube.com/embed/ZckylT7vbxs', "Nico's Troubles"],
['214', 'https://www.youtube.com/embed/0TFu8Pa-zAg', 'Finally Turning 20'],
['216', 'https://www.youtube.com/embed/wxn67jT7ws4', 'A Princess on Ice'],
['217', 'https://www.youtube.com/embed/QP7G5ZvUC4o', 'Home Cooking'],
['219', 'https://www.youtube.com/embed/beHvYwSMcmc', 'Purification'],
['220', 'https://www.youtube.com/embed/drpl_uSUsWk', 'The Age for Teasing'],
['221', 'https://www.youtube.com/embed/5_x6EzBxFwk', 'Resolution'],
['222', 'https://www.youtube.com/embed/5S8oDaOgszQ', 'Something Important'],
['224', 'https://www.youtube.com/embed/ECXxo8X0wGg', 'Omikuji Fortunes'],
['225', 'https://www.youtube.com/embed/aZF8p7JSmqU', 'After Class One Day'],
['226', 'https://www.youtube.com/embed/y7lkwgryfak', 'Things I Want to Try'],
['227', 'https://www.youtube.com/embed/pIeBh11XG54', 'Things I Want to Try'],
['228', 'https://www.youtube.com/embed/U2WMmiWzpS0', 'Things I Want to Try'],
['229', 'https://www.youtube.com/embed/u2sAFdgK6Bc', 'Things I Want to Try'],
['230', 'https://www.youtube.com/embed/uWdOIWqrBAM', 'Things I Want to Try'],
['231', 'https://www.youtube.com/embed/jNG2ilB1SHg', 'Things I Want to Try'],
['232', 'https://www.youtube.com/embed/75c8j1eKsYw', 'Things I Want to Try'],
['233', 'https://www.youtube.com/embed/q0qKFkK99oI', 'Things I Want to Try'],
['234', 'https://www.youtube.com/embed/SRMYphBvi0c', 'Things I Want to Try'],
['245', 'https://www.youtube.com/embed/xErG5ARAwg8', 'I Bought Plenty'],
['246', 'https://www.youtube.com/embed/7vMq3EJyvTQ', 'All the Thanks I Need'],
['247', 'https://www.youtube.com/embed/0PK0bcYNFCk', 'A Major Secret'],
['248', 'https://www.youtube.com/embed/WQguFyNNhtY', 'Can I Say It Right?'],
['250', 'https://www.youtube.com/embed/OdNon4HB97w', 'Listen to Me!'],
['252', 'https://www.youtube.com/embed/Mp3eKi4y7gY', 'Winter Mornings + You'],
['254', 'https://www.youtube.com/embed/UNc9yzaaWvw', 'Expressing Feelings'],
['255', 'https://www.youtube.com/embed/YR-Ln7P0-pY', 'I Was Looking for You!'],
['256', 'https://www.youtube.com/embed/jPm7ELZz3ec', "It'll Work"],
['257', 'https://www.youtube.com/embed/flaKjq_iy3g', 'Persistence'],
['259', 'https://www.youtube.com/embed/uLXQPZ24Ld4', 'A Fair Fight'],
['261', 'https://www.youtube.com/embed/EVpBBuyR_ps', 'Springtime Fun is Here'],
['262', 'https://www.youtube.com/embed/BbTPcFboMAk', 'Protecting Everyone'],
['263', 'https://www.youtube.com/embed/hb8h7FKJcyk', "I'm Nervous"],
['264', 'https://www.youtube.com/embed/T1QwvjWfwO8', 'The Season of Tickling'],
['265', 'https://www.youtube.com/embed/PF0Mj4uNOi0', 'A Different Hanayo'],
['267', 'https://www.youtube.com/embed/z0dzNdTee_0', "I'll Never Forgive!"],
['269', 'https://www.youtube.com/embed/d1FNB0OTw_o', "Kotori's Nap Lesson"],
['270', 'https://www.youtube.com/embed/JKqGyKDICR0', 'Spring of Goodbyes?'],
['271', 'https://www.youtube.com/embed/1joIeOr9q40', 'Season of Nico'],
['272', 'https://www.youtube.com/embed/FeJSwRj0Hbs', "I Can't Sleep Now! "],
['274', 'https://www.youtube.com/embed/hE53wEs-QcE', 'Birdwatching'],
['276', 'https://www.youtube.com/embed/eVRmDOyW5Cs', 'I Love Sweets!'],
['277', 'https://www.youtube.com/embed/AXuhnZrLj9o', 'Good for the Skin'],
['278', 'https://www.youtube.com/embed/9aA5ZnmscNE', 'What Are Sweets?'],
['279', 'https://www.youtube.com/embed/NxcoXQMgaPU', 'All Kinds!'],
['280', 'https://www.youtube.com/embed/PtplCsqv2B8', 'With Alisa'],
['282', 'https://www.youtube.com/embed/lHMFvNyUHoE', 'A Small Matter'],
['284', 'https://www.youtube.com/embed/fKSKauo5r30', 'What I Like'],
['285', 'https://www.youtube.com/embed/7ilCurylQe4', 'What I Like'],
['286', 'https://www.youtube.com/embed/O7X-IuXq_Dg', 'What I Like'],
['287', 'https://www.youtube.com/embed/5Dt1z36UdnY', 'What I Like'],
['288', 'https://www.youtube.com/embed/5TLMOe2KmFQ', 'What I Like'],
['289', 'https://www.youtube.com/embed/TAae-y3zj6s', 'What I Like'],
['290', 'https://www.youtube.com/embed/9LRvEoFznI8', 'What I Like'],
['291', 'https://www.youtube.com/embed/9uoVoM3Nsr4', 'What I Like'],
['292', 'https://www.youtube.com/embed/MOi5on_JCWM', 'What I Like'],
['293', 'https://www.youtube.com/embed/4OBJkL6sTfc', 'An Original'],
['294', 'https://www.youtube.com/embed/dq10KrGtQVM', "Enjoy Nature's Gifts"],
['295', 'https://www.youtube.com/embed/j5GRZDVTA-Q', 'Nico-esque, Right?'],
['296', 'https://www.youtube.com/embed/IRQt57twkYs', 'Learning from Candy'],
['298', 'https://www.youtube.com/embed/GhvrEf7GkMU', 'Small Miracles'] ,
['299', 'https://www.youtube.com/embed/AkO4tU8_Xgg', 'Small Miracles'],
['300', 'https://www.youtube.com/embed/fqksqbU7JaE', 'Small Miracles'],
['301', 'https://www.youtube.com/embed/UUWF2T800qs', 'Small Miracles'],
['302', 'https://www.youtube.com/embed/4Ir5FK0OaMk', 'Small Miracles'],
['303', 'https://www.youtube.com/embed/rTw60IgNNrc', 'Small Miracles'],
['304', 'https://www.youtube.com/embed/Tq7nBxb5VDQ', 'Small Miracles'],
['305', 'https://www.youtube.com/embed/RB6GoUbLnc4', 'Small Miracles'],
['306', 'https://www.youtube.com/embed/QpHvGIrpYjM', 'Small Miracles'],
['308', 'https://www.youtube.com/embed/KLARQ-3bZHc', 'After the Clam Hunt'],
['311', 'https://www.youtube.com/embed/cqH4T1XgPOg', "The Crane's Feelings"],
['312', 'https://www.youtube.com/embed/WA3617MG2sc', 'That Lamp Guy!'],
['313', 'https://www.youtube.com/embed/LYaziXxYwo4', 'Destiny and True Love'],
['314', 'https://www.youtube.com/embed/TbVL57BFBDY', 'A Destined Meeting'],
['315', 'https://www.youtube.com/embed/Ux8pEyhHOrA', 'I Shrank!'],
['317', 'https://www.youtube.com/embed/m-Xgl_sEPL0', "Boys' Day"],
['319', 'https://www.youtube.com/embed/3PbE884-DWw', 'The Best Fairy Tale!'],
['320', 'https://www.youtube.com/embed/lAEzHzuICHY', 'I Wanted to Show You'],
['321', 'https://www.youtube.com/embed/ZGdFiZoaynA', "Even I'm Amazed"],
['322', 'https://www.youtube.com/embed/T7qyfHDneF0', 'A Fun Fairy Tale'],
['324', 'https://www.youtube.com/embed/sfTtEYzS6N8', 'Caught You Being Nice'],
['326', 'https://www.youtube.com/embed/ztutlZpnQAg', 'Nice Costumes'],
['327', 'https://www.youtube.com/embed/sEi6yP_Avw4', 'How Is It So Heavy?'],
['328', 'https://www.youtube.com/embed/F58x295WP-Y', 'You Can Do Anything'],
['329', 'https://www.youtube.com/embed/S6X0Qp1frJY', 'Waiting My Whole Life'],
['330', 'https://www.youtube.com/embed/S1HtrP2EvsQ', "I Can't Imagine"],
['332', 'https://www.youtube.com/embed/x1BibplUNXw', "We're Fine Together"],
['334', 'https://www.youtube.com/embed/YP2ykMVvKxg', 'Winter Means...'],
['335', 'https://www.youtube.com/embed/_qWbMgmYqBA', 'Winter Means...'],
['336', 'https://www.youtube.com/embed/Iql0BFD84cQ', 'Winter Means...'],
['337', 'https://www.youtube.com/embed/FQRmJBGHpq8', 'Winter Means...'],
['338', 'https://www.youtube.com/embed/cF0KSBbfO2o', 'Winter Means...'],
['339', 'https://www.youtube.com/embed/Fqura1dwuM4', 'Winter Means...'],
['340', 'https://www.youtube.com/embed/qNtKNvVYpuo', 'Winter Means...'],
['341', 'https://www.youtube.com/embed/H-_g-g0ZX9E', 'Winter Means...'],
['342', 'https://www.youtube.com/embed/9r6lsovUa54', 'Winter Means...'],
['343', 'https://www.youtube.com/embed/31toW9prW4U', 'Invited'],
['344', 'https://www.youtube.com/embed/FqkpzWeYyzg', 'Every Party'],
['345', 'https://www.youtube.com/embed/DwDNVrT_cyU', 'Dresses'],
['346', 'https://www.youtube.com/embed/PsL9ZZR72q8', 'Some Future Day'],
['349', 'https://www.youtube.com/embed/kAKk0ovrNMg', 'Declaring Victory!'],
['350', 'https://www.youtube.com/embed/2X0WpMrfNk4', 'A Passing Shower'],
['354', 'https://www.youtube.com/embed/Pf3JpwTOz7M', "Of Course It'll be Fun"],
['355', 'https://www.youtube.com/embed/WTx-3-FiEs8', 'Looking for Mermaids'],
['356', 'https://www.youtube.com/embed/3xMADXvvM_A', 'Possible Mermaid'],
['357', 'https://www.youtube.com/embed/gcSXqm98DQo', 'Showing Charm'],
['358', 'https://www.youtube.com/embed/3R6_oZNLPzk', "Don't Get Serious me"],
['360', 'https://www.youtube.com/embed/-l4D5CksWzQ', 'Students Are Busy!'],
['364', 'https://www.youtube.com/embed/JMV_Zknm-FU', 'A Whole New World'],
['365', 'https://www.youtube.com/embed/rL-X9JktR8I', "Kotori's Store"],
['367', 'https://www.youtube.com/embed/GIDcjIP7JE8', 'A Surprising Side'],
['369', 'https://www.youtube.com/embed/RsvgVNnTq-I', 'This Day, We Fight'],
['370', 'https://www.youtube.com/embed/G4HDxqGt_IM', 'Together at the Beach'],
['374', 'https://www.youtube.com/embed/jybrFG8PTyc', 'Words to Remember'],
['375', 'https://www.youtube.com/embed/V_gmjIINOrE', 'Nine Beautiful Girls'],
['376', 'https://www.youtube.com/embed/QWHhsyxxhjk', "I'll Come to Save You"],
['377', 'https://www.youtube.com/embed/qaJ8ltDN6fQ', 'Have Some Tea'],
['378', 'https://www.youtube.com/embed/jencXr6p85U', 'Mesmerizing Silk'],
['392', 'https://www.youtube.com/embed/KjQEqnIaS0o', 'Bored at the Pool'],
['394', 'https://www.youtube.com/embed/FZt_a3__qJ0', 'What I Want You to See'],
['395', 'https://www.youtube.com/embed/dpPPEkF2Z_c', 'It Comes Naturally'],
['396', 'https://www.youtube.com/embed/2Gxsr0sDeCQ', 'Long, Long Legs'],
['397', 'https://www.youtube.com/embed/0FdKpWl27I4', "Nico's Love Gourmet"],
['399', 'https://www.youtube.com/embed/2HY9MISFfwM', 'I Wanna Go Home...'],
['400', 'https://www.youtube.com/embed/xzq69yVUkOA', 'I Can Do It Better'],
['401', 'https://www.youtube.com/embed/sTef0xHbPDw', 'Strategy Session!'],
['404', 'https://www.youtube.com/embed/HsFxtHJKiV0', 'Details Are Important!'],
['405', 'https://www.youtube.com/embed/D_roGtBGa0k', 'Are You Listening?'],
['406', 'https://www.youtube.com/embed/Xq8SDd0_olU', 'A Great Reward'],
['407', 'https://www.youtube.com/embed/_PwPcDHj5Gk', 'It Would Be a Waste'],
['408', 'https://www.youtube.com/embed/nV9x_PzOcoU', 'Even Just for Today'],
['410', 'https://www.youtube.com/embed/7Ag0G4oKPxM', "Let's Enjoy it All!"],
['412', 'https://www.youtube.com/embed/vfoi2CB4KjM', "I'll Do It My Way!"],
['413', 'https://www.youtube.com/embed/RC1WzChXMTY', 'Tie It Tight'],
['414', 'https://www.youtube.com/embed/ZTwVT2MDi0E', 'In Your Eyes...'],
['415', 'https://www.youtube.com/embed/P_-uOmIqd9M', 'Carried Away']
];
