var storyAr = 
[
['28', 'https://www.youtube.com/embed/-KNyYK4n60k', 'Speaking of Summer...'],
['29', 'https://www.youtube.com/embed/omNbdaPgpdM', 'Speaking of Summer...'],
['30', 'https://www.youtube.com/embed/wk5EJtmO51s', 'Speaking of Summer...'],
['31', 'https://www.youtube.com/embed/85mbXy0e7EE', 'Speaking of Summer...'],
['32', 'https://www.youtube.com/embed/85mbXy0e7EE', 'Speaking of Summer...'],
['33', 'https://www.youtube.com/embed/jRXKMzu8_4I', 'Speaking of Summer...'],
['34', 'https://www.youtube.com/embed/vDj697_MkKM', 'Speaking of Summer...'],
['35', 'https://www.youtube.com/embed/AI1zBJhol9Q', 'Speaking of Summer...'],
['36', 'https://www.youtube.com/embed/WNQaLyU8glE', 'Speaking of Summer...'],
['37', 'https://www.youtube.com/embed/4yG2sVGzF-A', 'If I Knew Magic...'],
['38', 'https://www.youtube.com/embed/NKpCNtqcSxE', 'If I Knew Magic...'],
['39', 'https://www.youtube.com/embed/TcdDq5RdEAk', 'If I Knew Magic...'],
['40', 'https://www.youtube.com/embed/0y4rGoHMFY8', 'If I Knew Magic...'],
['41', 'https://www.youtube.com/embed/F1chXJ_piao', 'If I Knew Magic...'],
['42', 'https://www.youtube.com/embed/7i7pyImLgTo', 'If I Knew Magic...'],
['43', 'https://www.youtube.com/embed/7i7pyImLgTo', 'If I Knew Magic...'],
['44', 'https://www.youtube.com/embed/N-Gnt4zFrhQ', 'If I Knew Magic...'],
['45', 'https://www.youtube.com/embed/ZGOBzwRqIRU', 'If I Knew Magic...'],
['46', 'https://www.youtube.com/embed/bwYxp3w7brU', 'A Place To Go'],
['47', 'https://www.youtube.com/embed/eD8AhQL4Vjo', 'A Place To Go'],
['48', 'https://www.youtube.com/embed/Ft43pDyacY0', 'A Place To Go'],
['49', 'https://www.youtube.com/embed/al7E-HRKncQ', 'A Place To Go'],
['50', 'https://www.youtube.com/embed/yQd16PYUecw', 'A Place To Go'],
['51', 'https://www.youtube.com/embed/ZW5a4Sxg-G8', 'A Place To Go'],
['52', 'https://www.youtube.com/embed/uJHLpb7nkxk', 'A Place To Go'],
['53', 'https://www.youtube.com/embed/5ijlOm4QCyE', 'A Place To Go'],
['54', 'https://www.youtube.com/embed/E_Ruy-rdJCQ', 'A Place To Go'],
['55', 'https://www.youtube.com/embed/xf_HsxwzzGE', 'School Idol Dream'],
['56', 'https://www.youtube.com/embed/wYTeRTYSMdI', 'Victory Goddess'],
['57', 'https://www.youtube.com/embed/geH95F79u5c', 'Your Nurse'],
['58', 'https://www.youtube.com/embed/-yo3964jsF4', 'School Protector'],
['59', 'https://www.youtube.com/embed/z3GstmEQfd0', 'Aiming for a Heart'],
['60', 'https://www.youtube.com/embed/9pzOZLUV_lo', 'Dress-Up'],
['61', 'https://www.youtube.com/embed/XWxxFnC7ZE4', 'Lucky Power'],
['62', 'https://www.youtube.com/embed/4CW0yDzRW18', "I'm Embarrassed..."],
['63', 'https://www.youtube.com/embed/pBZX0DatBwU', "That's the Setting?"],
['64', 'https://www.youtube.com/embed/1MIYMPB8_CE', 'Inspirational Girl'],
['65', 'https://www.youtube.com/embed/HUkEOBPNUwY', 'With Bean Jam!'],
['66', 'https://www.youtube.com/embed/IgfJe4xDbns', 'Super-Popular Nico'],
['71', 'https://www.youtube.com/embed/Wkn5FEm8-ZU', 'Firefighter'],
['72', 'https://www.youtube.com/embed/sAEFA8KurTg', 'Always on the Mark!'],
['73', 'https://www.youtube.com/embed/JlaiAx69MOE', 'Cupid of Love'],
['75', 'https://www.youtube.com/embed/ZaUb9zB97TE', 'Sheepish Kotori'],
['77', 'https://www.youtube.com/embed/a0J_AuKJYQg', "Maki's Exam Room"],
['78', 'https://www.youtube.com/embed/OftuRC-K3Rw ', 'Clumsy Hanayo'],
['79', 'https://www.youtube.com/embed/_IOs8u1ZOaY', 'Super Idol'],
['81', 'https://www.youtube.com/embed/ofg2KMs3N4c', "A Rabbit's Feelings"],
['83', 'https://www.youtube.com/embed/SnlUZCIrNUQ', 'Alpaca Scene'],
['86', 'https://www.youtube.com/embed/-QR-VPZTZQE', 'School Protector'],
['87', 'https://www.youtube.com/embed/ER2Fjgyaeyg', 'Your Guide'],
['88', 'https://www.youtube.com/embed/Ixs_SMgkHNI', 'An Angel!'],
['90', 'https://www.youtube.com/embed/m-79vjLZTiI', 'Most Popular One'],
['92', 'https://www.youtube.com/embed/ZdI0PARdMHk', 'Sweet Kotori'],
['93', 'https://www.youtube.com/embed/-xpQ5t4pygA', 'Speaking of Rin..'],
['94', 'https://www.youtube.com/embed/CTLU0pw_-Lk', 'Mystery Thief Elichika'],
['99', 'https://www.youtube.com/embed/FzbfF7vtWKs', 'Any Costume'],
['100', 'https://www.youtube.com/embed/uTmbNJYar7w', 'Just Understand it!'],
['101', 'https://www.youtube.com/embed/6ZAY8rvFoxU', 'The Destined One'],
['103', 'https://www.youtube.com/embed/gadMwFx4mKY', 'Tell Me How You Feel'],
['104', 'https://www.youtube.com/embed/GhCJZ4rjpKE', 'Lucky Charm'],
['105', 'https://www.youtube.com/embed/AUqgDwk2Hfw', "Rin's Ramen"],
['107', 'https://www.youtube.com/embed/iit9IMtWFFg', 'The Forest Bear'],
['122', 'https://www.youtube.com/embed/-lJhe5KgIHY', 'Summer Love Action!'],
['123', 'https://www.youtube.com/embed/dFnxuHPpi7U', 'Not Enough Sleep'],
['124', 'https://www.youtube.com/embed/uOXZGfqgyZA', 'Summer Vow'],
['125', 'https://www.youtube.com/embed/Sws3Izm7blY', 'Elephant Sprinkler'],
['126', 'https://www.youtube.com/embed/CsoHKXYBHfU', 'Everyone on Stage'],
['127', 'https://www.youtube.com/embed/h-9V_t5pyU8', 'Private Summer'],
['129', 'https://www.youtube.com/embed/50bcRVJiBCA', 'Fluffy Tail'],
['131', 'https://www.youtube.com/embed/q2sj6kWZPdI', 'Kotori and the Pool'],
['132', 'https://www.youtube.com/embed/6d2CtD-Fbxw', "I'm Yours"],
['133', 'https://www.youtube.com/embed/U6pk28EPJdU', 'Being Prepared!'],
['134', 'https://www.youtube.com/embed/KqXJy1UiN_k', 'Cute Bikini Girls'],
['136', 'https://www.youtube.com/embed/lfjXR2rfn-Q', 'Strange Feeling'],
['141', 'https://www.youtube.com/embed/05-LozS5yRg', 'I Love Summer'],
['142', 'https://www.youtube.com/embed/2ccoAmeqOyc', 'No, Not That'],
['143', 'https://www.youtube.com/embed/SFbHlfj5ijc', 'The Lost Voice'],
['144', 'https://www.youtube.com/embed/p5Kz1bRYDMU', 'Summer Miracle'],
['145', 'https://www.youtube.com/embed/v7dCn0skAf4', 'Shared Feelings'],
['150', 'https://www.youtube.com/embed/yphcTLq6pQ8', 'Touchy Spirits'],
['152', 'https://www.youtube.com/embed/eicBMS2YYew', 'Be More Forceful ♪'],
['153', 'https://www.youtube.com/embed/eDbWRx_QWeg', 'Summerfest Appeal'],
['154', 'https://www.youtube.com/embed/uRECSkg2QXM', 'Grown-Up Stairway'],
['155', 'https://www.youtube.com/embed/g3cThtohPbU', 'Tell Me, Tell Me!'],
['157', 'https://www.youtube.com/embed/zw5Dap4ItYY', 'Dumpling Party'],
['161', 'https://www.youtube.com/embed/3bQ0MHqtoIg', 'Race for Love'],
['162', 'https://www.youtube.com/embed/kqhZMkcYpMo', 'Beloved Sports Idol'],
['163', 'https://www.youtube.com/embed/Iyq80LyZq5M', 'Cheering for Us'],
['164', 'https://www.youtube.com/embed/XVKkdh4seSE', "I'm Getting Nervous"],
['165', 'https://www.youtube.com/embed/0dlq-D0KiV8', 'Take on the Challenge!'],
['167', 'https://www.youtube.com/embed/i6FAiNZsWB4', 'Master of the House'],
['169', 'https://www.youtube.com/embed/jYYxMlsCca8', 'Worry and Stress!'],
['170', 'https://www.youtube.com/embed/ygfBzIiXdFc', "You're So Tricky!"],
['171', 'https://www.youtube.com/embed/SA9GFW6XA-Q', 'No Credit'],
['172', 'https://www.youtube.com/embed/qKJVBUgN6I4', 'Scavenger Hunt'],
['174', 'https://www.youtube.com/embed/mrd9Db0V5Ng', 'Secrets from the Book'],
['176', 'https://www.youtube.com/embed/XxQTPQ7PhCE', 'Special Dish'],
['177', 'https://www.youtube.com/embed/CUj0hz2hdrw', "Elichika's Special"],
['178', 'https://www.youtube.com/embed/5P_cy2Ow8Lw', 'Simmering Stew'],
['179', 'https://www.youtube.com/embed/g3ZZJB2A_hU', 'Homely Smile'],
['180', 'https://www.youtube.com/embed/75q8Dlq5Ti0', 'Hibernation'],
['182', 'https://www.youtube.com/embed/l_Aq-BGAPuU', 'Lucky Charm'],
['184', 'https://www.youtube.com/embed/o01w7eaKWZE', 'Full of Nutrition'],
['185', 'https://www.youtube.com/embed/ZWdmDFjpXKM', 'My Special Ramen'],
['186', 'https://www.youtube.com/embed/odm2fAJhKKQ', 'Quick Recipe'],
['187', 'https://www.youtube.com/embed/2x8LSpFHrbY', 'Ordinary Lunch'],
['189', 'https://www.youtube.com/embed/x7Z9q0UA254', 'Tingly Heart'],
['192', 'https://www.youtube.com/embed/cI-0BKrb__Q', 'Miraculous Night'],
['193', 'https://www.youtube.com/embed/SeP3PodMLJc', 'No Food No Problem'],
['194', 'https://www.youtube.com/embed/O4DqEj2zghw', 'Christmas Memories'],
['195', 'https://www.youtube.com/embed/9uMRNtE2f6k', 'True Art'],
['196', 'https://www.youtube.com/embed/03CdCFsMJEQ', 'Were You Being Good?'],
['198', 'https://www.youtube.com/embed/q-9RWqmNHyg', 'Skating Together'],
['200', 'https://www.youtube.com/embed/oT4-AGZ15Ag', 'Christmas??'],
['201', 'https://www.youtube.com/embed/j81t5U2gQjs', 'Santa Kotori'],
['202', 'https://www.youtube.com/embed/dqzgvVT0xCg', 'The Magical Lunchbox'],
['203', 'https://www.youtube.com/embed/j1q0S7jEkgg', 'A Gift from My Heart'],
['204', 'https://www.youtube.com/embed/HfzAnbFKGjo', 'Snowman, Kotori Style'],
['206', 'https://www.youtube.com/embed/7l27COnX088', 'A Special Somebody'],
['207', 'https://www.youtube.com/embed/4Wygue1z5oo', 'Can I be your Present?'],
['210', 'https://www.youtube.com/embed/XXMiZcJu2Aw', 'My Source of Happiness'],
['211', 'https://www.youtube.com/embed/6Z_rDn2ExbA', 'Give Me a Good Fortune'],
['212', 'https://www.youtube.com/embed/UEW21jC2gko', 'New Year Greetings'],
['213', 'https://www.youtube.com/embed/ZckylT7vbxs', "Nico's Troubles"],
['214', 'https://www.youtube.com/embed/0TFu8Pa-zAg', 'Finally Turning 20'],
['216', 'https://www.youtube.com/embed/wxn67jT7ws4', 'A Princess on Ice'],
['217', 'https://www.youtube.com/embed/QP7G5ZvUC4o', 'Home Cooking'],
['219', 'https://www.youtube.com/embed/beHvYwSMcmc', 'Purification'],
['220', 'https://www.youtube.com/embed/drpl_uSUsWk', 'The Age for Teasing'],
['221', 'https://www.youtube.com/embed/5_x6EzBxFwk', 'Resolution'],
['222', 'https://www.youtube.com/embed/5S8oDaOgszQ', 'Something Important'],
['224', 'https://www.youtube.com/embed/ECXxo8X0wGg', 'Omikuji Fortunes'],
['225', 'https://www.youtube.com/embed/aZF8p7JSmqU', 'After Class One Day'],
['226', 'https://www.youtube.com/embed/y7lkwgryfak', 'Things I Want to Try'],
['227', 'https://www.youtube.com/embed/pIeBh11XG54', 'Things I Want to Try'],
['228', 'https://www.youtube.com/embed/U2WMmiWzpS0', 'Things I Want to Try'],
['229', 'https://www.youtube.com/embed/u2sAFdgK6Bc', 'Things I Want to Try'],
['230', 'https://www.youtube.com/embed/uWdOIWqrBAM', 'Things I Want to Try'],
['231', 'https://www.youtube.com/embed/jNG2ilB1SHg', 'Things I Want to Try'],
['232', 'https://www.youtube.com/embed/75c8j1eKsYw', 'Things I Want to Try'],
['233', 'https://www.youtube.com/embed/q0qKFkK99oI', 'Things I Want to Try'],
['234', 'https://www.youtube.com/embed/SRMYphBvi0c', 'Things I Want to Try'],
['245', 'https://www.youtube.com/embed/xErG5ARAwg8', 'I Bought Plenty'],
['246', 'https://www.youtube.com/embed/7vMq3EJyvTQ', 'All the Thanks I Need'],
['247', 'https://www.youtube.com/embed/0PK0bcYNFCk', 'A Major Secret'],
['248', 'https://www.youtube.com/embed/WQguFyNNhtY', 'Can I Say It Right?'],
['250', 'https://www.youtube.com/embed/OdNon4HB97w', 'Listen to Me!'],
['252', 'https://www.youtube.com/embed/Mp3eKi4y7gY', 'Winter Mornings + You'],
['254', 'https://www.youtube.com/embed/UNc9yzaaWvw', 'Expressing Feelings'],
['255', 'https://www.youtube.com/embed/YR-Ln7P0-pY', 'I Was Looking for You!'],
['256', 'https://www.youtube.com/embed/jPm7ELZz3ec', "It'll Work"],
['257', 'https://www.youtube.com/embed/flaKjq_iy3g', 'Persistence'],
['259', 'https://www.youtube.com/embed/uLXQPZ24Ld4', 'A Fair Fight'],
['261', 'https://www.youtube.com/embed/EVpBBuyR_ps', 'Springtime Fun is Here'],
['262', 'https://www.youtube.com/embed/BbTPcFboMAk', 'Protecting Everyone'],
['263', 'https://www.youtube.com/embed/hb8h7FKJcyk', "I'm Nervous"],
['264', 'https://www.youtube.com/embed/T1QwvjWfwO8', 'The Season of Tickling'],
['265', 'https://www.youtube.com/embed/PF0Mj4uNOi0', 'A Different Hanayo'],
['267', 'https://www.youtube.com/embed/z0dzNdTee_0', "I'll Never Forgive!"],
['269', 'https://www.youtube.com/embed/d1FNB0OTw_o', "Kotori's Nap Lesson"],
['270', 'https://www.youtube.com/embed/JKqGyKDICR0', 'Spring of Goodbyes?'],
['271', 'https://www.youtube.com/embed/1joIeOr9q40', 'Season of Nico'],
['272', 'https://www.youtube.com/embed/FeJSwRj0Hbs', "I Can't Sleep Now! "],
['274', 'https://www.youtube.com/embed/hE53wEs-QcE', 'Birdwatching'],
['276', 'https://www.youtube.com/embed/eVRmDOyW5Cs', 'I Love Sweets!'],
['277', 'https://www.youtube.com/embed/AXuhnZrLj9o', 'Good for the Skin'],
['278', 'https://www.youtube.com/embed/9aA5ZnmscNE', 'What Are Sweets?'],
['279', 'https://www.youtube.com/embed/NxcoXQMgaPU', 'All Kinds!'],
['280', 'https://www.youtube.com/embed/PtplCsqv2B8', 'With Alisa'],
['282', 'https://www.youtube.com/embed/lHMFvNyUHoE', 'A Small Matter'],
['284', 'https://www.youtube.com/embed/fKSKauo5r30', 'What I Like'],
['285', 'https://www.youtube.com/embed/7ilCurylQe4', 'What I Like'],
['286', 'https://www.youtube.com/embed/O7X-IuXq_Dg', 'What I Like'],
['287', 'https://www.youtube.com/embed/5Dt1z36UdnY', 'What I Like'],
['288', 'https://www.youtube.com/embed/5TLMOe2KmFQ', 'What I Like'],
['289', 'https://www.youtube.com/embed/TAae-y3zj6s', 'What I Like'],
['290', 'https://www.youtube.com/embed/9LRvEoFznI8', 'What I Like'],
['291', 'https://www.youtube.com/embed/9uoVoM3Nsr4', 'What I Like'],
['292', 'https://www.youtube.com/embed/MOi5on_JCWM', 'What I Like'],
['293', 'https://www.youtube.com/embed/4OBJkL6sTfc', 'An Original'],
['294', 'https://www.youtube.com/embed/dq10KrGtQVM', "Enjoy Nature's Gifts"],
['295', 'https://www.youtube.com/embed/j5GRZDVTA-Q', 'Nico-esque, Right?'],
['296', 'https://www.youtube.com/embed/IRQt57twkYs', 'Learning from Candy'],
['298', 'https://www.youtube.com/embed/GhvrEf7GkMU', 'Small Miracles'] ,
['299', 'https://www.youtube.com/embed/AkO4tU8_Xgg', 'Small Miracles'],
['300', 'https://www.youtube.com/embed/fqksqbU7JaE', 'Small Miracles'],
['301', 'https://www.youtube.com/embed/UUWF2T800qs', 'Small Miracles'],
['302', 'https://www.youtube.com/embed/4Ir5FK0OaMk', 'Small Miracles'],
['303', 'https://www.youtube.com/embed/rTw60IgNNrc', 'Small Miracles'],
['304', 'https://www.youtube.com/embed/Tq7nBxb5VDQ', 'Small Miracles'],
['305', 'https://www.youtube.com/embed/RB6GoUbLnc4', 'Small Miracles'],
['306', 'https://www.youtube.com/embed/QpHvGIrpYjM', 'Small Miracles'],
['308', 'https://www.youtube.com/embed/KLARQ-3bZHc', 'After the Clam Hunt'],
['311', 'https://www.youtube.com/embed/cqH4T1XgPOg', "The Crane's Feelings"],
['312', 'https://www.youtube.com/embed/WA3617MG2sc', 'That Lamp Guy!'],
['313', 'https://www.youtube.com/embed/LYaziXxYwo4', 'Destiny and True Love'],
['314', 'https://www.youtube.com/embed/TbVL57BFBDY', 'A Destined Meeting'],
['315', 'https://www.youtube.com/embed/Ux8pEyhHOrA', 'I Shrank!'],
['317', 'https://www.youtube.com/embed/m-Xgl_sEPL0', "Boys' Day"],
['319', 'https://www.youtube.com/embed/3PbE884-DWw', 'The Best Fairy Tale!'],
['320', 'https://www.youtube.com/embed/lAEzHzuICHY', 'I Wanted to Show You'],
['321', 'https://www.youtube.com/embed/ZGdFiZoaynA', "Even I'm Amazed"],
['322', 'https://www.youtube.com/embed/T7qyfHDneF0', 'A Fun Fairy Tale'],
['324', 'https://www.youtube.com/embed/sfTtEYzS6N8', 'Caught You Being Nice'],
['326', 'https://www.youtube.com/embed/ztutlZpnQAg', 'Nice Costumes'],
['327', 'https://www.youtube.com/embed/sEi6yP_Avw4', 'How Is It So Heavy?'],
['328', 'https://www.youtube.com/embed/F58x295WP-Y', 'You Can Do Anything'],
['329', 'https://www.youtube.com/embed/S6X0Qp1frJY', 'Waiting My Whole Life'],
['330', 'https://www.youtube.com/embed/S1HtrP2EvsQ', "I Can't Imagine"],
['332', 'https://www.youtube.com/embed/x1BibplUNXw', "We're Fine Together"],
['334', 'https://www.youtube.com/embed/YP2ykMVvKxg', 'Winter Means...'],
['335', 'https://www.youtube.com/embed/_qWbMgmYqBA', 'Winter Means...'],
['336', 'https://www.youtube.com/embed/Iql0BFD84cQ', 'Winter Means...'],
['337', 'https://www.youtube.com/embed/FQRmJBGHpq8', 'Winter Means...'],
['338', 'https://www.youtube.com/embed/cF0KSBbfO2o', 'Winter Means...'],
['339', 'https://www.youtube.com/embed/Fqura1dwuM4', 'Winter Means...'],
['340', 'https://www.youtube.com/embed/qNtKNvVYpuo', 'Winter Means...'],
['341', 'https://www.youtube.com/embed/H-_g-g0ZX9E', 'Winter Means...'],
['342', 'https://www.youtube.com/embed/9r6lsovUa54', 'Winter Means...'],
['343', 'https://www.youtube.com/embed/31toW9prW4U', 'Invited'],
['344', 'https://www.youtube.com/embed/FqkpzWeYyzg', 'Every Party'],
['345', 'https://www.youtube.com/embed/DwDNVrT_cyU', 'Dresses'],
['346', 'https://www.youtube.com/embed/PsL9ZZR72q8', 'Some Future Day'],
['349', 'https://www.youtube.com/embed/kAKk0ovrNMg', 'Declaring Victory!'],
['350', 'https://www.youtube.com/embed/2X0WpMrfNk4', 'A Passing Shower'],
['354', 'https://www.youtube.com/embed/Pf3JpwTOz7M', "Of Course It'll be Fun"],
['355', 'https://www.youtube.com/embed/WTx-3-FiEs8', 'Looking for Mermaids'],
['356', 'https://www.youtube.com/embed/3xMADXvvM_A', 'Possible Mermaid'],
['357', 'https://www.youtube.com/embed/gcSXqm98DQo', 'Showing Charm'],
['358', 'https://www.youtube.com/embed/3R6_oZNLPzk', "Don't Get Serious me"],
['360', 'https://www.youtube.com/embed/-l4D5CksWzQ', 'Students Are Busy!'],
['364', 'https://www.youtube.com/embed/JMV_Zknm-FU', 'A Whole New World'],
['365', 'https://www.youtube.com/embed/rL-X9JktR8I', "Kotori's Store"],
['367', 'https://www.youtube.com/embed/GIDcjIP7JE8', 'A Surprising Side'],
['369', 'https://www.youtube.com/embed/RsvgVNnTq-I', 'This Day, We Fight'],
['370', 'https://www.youtube.com/embed/G4HDxqGt_IM', 'Together at the Beach'],
['374', 'https://www.youtube.com/embed/jybrFG8PTyc', 'Words to Remember'],
['375', 'https://www.youtube.com/embed/V_gmjIINOrE', 'Nine Beautiful Girls'],
['376', 'https://www.youtube.com/embed/QWHhsyxxhjk', "I'll Come to Save You"],
['377', 'https://www.youtube.com/embed/qaJ8ltDN6fQ', 'Have Some Tea'],
['378', 'https://www.youtube.com/embed/jencXr6p85U', 'Mesmerizing Silk'],
['382', 'https://www.youtube.com/embed/SnlUZCIrNUQ', 'Alpaca Scene'],
['392', 'https://www.youtube.com/embed/KjQEqnIaS0o', 'Bored at the Pool'],
['394', 'https://www.youtube.com/embed/FZt_a3__qJ0', 'What I Want You to See'],
['395', 'https://www.youtube.com/embed/dpPPEkF2Z_c', 'It Comes Naturally'],
['396', 'https://www.youtube.com/embed/2Gxsr0sDeCQ', 'Long, Long Legs'],
['397', 'https://www.youtube.com/embed/0FdKpWl27I4', "Nico's Love Gourmet"],
['399', 'https://www.youtube.com/embed/2HY9MISFfwM', 'I Wanna Go Home...'],
['400', 'https://www.youtube.com/embed/xzq69yVUkOA', 'I Can Do It Better'],
['401', 'https://www.youtube.com/embed/sTef0xHbPDw', 'Strategy Session!'],
['404', 'https://www.youtube.com/embed/HsFxtHJKiV0', 'Details Are Important!'],
['405', 'https://www.youtube.com/embed/D_roGtBGa0k', 'Are You Listening?'],
['406', 'https://www.youtube.com/embed/Xq8SDd0_olU', 'A Great Reward'],
['407', 'https://www.youtube.com/embed/_PwPcDHj5Gk', 'It Would Be a Waste'],
['408', 'https://www.youtube.com/embed/nV9x_PzOcoU', 'Even Just for Today'],
['410', 'https://www.youtube.com/embed/7Ag0G4oKPxM', "Let's Enjoy it All!"],
['412', 'https://www.youtube.com/embed/vfoi2CB4KjM', "I'll Do It My Way!"],
['413', 'https://www.youtube.com/embed/RC1WzChXMTY', 'Tie It Tight'],
['414', 'https://www.youtube.com/embed/ZTwVT2MDi0E', 'In Your Eyes...'],
['415', 'https://www.youtube.com/embed/P_-uOmIqd9M', 'Carried Away'],
['417', 'https://www.youtube.com/embed/FrasIRfvTFI', 'My Savior'],
['421', 'https://www.youtube.com/embed/7gTbXv3WPJY', 'One Day After School'],
['422', 'https://www.youtube.com/embed/TIgSd4c24Tg', 'Amusement Parks Rule!'],
['423', 'https://www.youtube.com/embed/lgKY56Qqv5w', "Don't Tease Me..."],
['424', 'https://www.youtube.com/embed/VVXrwDUBWso', 'A White Lie'],
['425', 'https://www.youtube.com/embed/SZfmvMcFn1c', 'Never Ending Parades'],
['426', 'https://www.youtube.com/embed/r1GmTAfuezE', "I'm Scared, but Okay!"],
['428', 'https://www.youtube.com/embed/pdt9AcSYKTw', "Hanayo's Musings"],
['430', 'https://www.youtube.com/embed/W8Tat5gBoK8', 'A Wish for the Future'],
['431', 'https://www.youtube.com/embed/aPgKzd381nk', 'A Wish for the Future'] ,
['432', 'https://www.youtube.com/embed/4wCLSD2lxZE', 'A Wish for the Future'] ,
['433', 'https://www.youtube.com/embed/gkAROvxHTWo', 'A Wish for the Future'] ,
['434', 'https://www.youtube.com/embed/w9wwc0IhGds' , "A Wish for the Future"] ,
['435', 'https://www.youtube.com/embed/T_KszMpckjw', 'A Wish for the Future'] ,
['436', 'https://www.youtube.com/embed/BUmT27uYzdk', 'A Wish for the Future'] ,
['437', 'https://www.youtube.com/embed/GHg0bujEkLE', 'A Wish for the Future'] ,
['438', 'https://www.youtube.com/embed/xsr4tjUDW7U', 'A Wish for the Future'],
['439', 'https://www.youtube.com/embed/ifIMt4HLMB0', 'Let Me Lead You'],
['440', 'https://www.youtube.com/embed/OC7O3OvnC0E', 'Kotori the Witch'],
['441', 'https://www.youtube.com/embed/pkHFnKTnhTo', 'Which Sounds Better'],
['444', 'https://www.youtube.com/embed/3pgvT3rl1SA', "Umi's a Meanie!"],
['447', 'https://www.youtube.com/embed/R8FAIJeR31g', 'She Should Try Harder!'],
['448', 'https://www.youtube.com/embed/UgyLHbVPRRg', 'Ghost Cat Ecology'],
['452', 'https://www.youtube.com/embed/MTwH9QaDZr0', "What's a Leo Like?"],
['453', 'https://www.youtube.com/embed/9NDkgmeI3qo', 'Kept by the Night Sky'],
['454', 'https://www.youtube.com/embed/OK-IZdcBalw', 'What Do You Think'],
['455', 'https://www.youtube.com/embed/eTg5QXnbahc', 'Something I Learned'],
['456', 'https://www.youtube.com/embed/MwuA7udOndg', 'Constellation Talk'],
['458', 'https://www.youtube.com/embed/wJydc5uCKUE', "I'm Worried About You"],
['460', 'https://www.youtube.com/embed/3_l2jMxMfPs', 'A Little While Ago'],
['461', 'https://www.youtube.com/embed/POoFcRi2ayM', 'Unchanged Feelings'],
['462', 'https://www.youtube.com/embed/lBUIYcwLJf4', 'Cancer Crab'],
['469', 'https://www.youtube.com/embed/kzlikEihryA', 'Tarot Reading'],
['472', 'https://www.youtube.com/embed/fbAga89wFko', "Let's Train!"],
['478', 'https://www.youtube.com/embed/hK6viGyrab0', 'Am I Overdoing It?'],
['482', 'https://www.youtube.com/embed/eXRALStlQ5g', 'Stay With Me'],
['483', 'https://www.youtube.com/embed/U7UKoEjfX7c', 'Hide Me!'],
['484', 'https://www.youtube.com/embed/xLtUksA03MI', 'Christmas Night'],
['487', 'https://www.youtube.com/embed/JZ6KVg8KHJs', "I'd Rather Not Say"],
['488', 'https://www.youtube.com/embed/UgyLHbVPRRg', 'Ghost Cat Ecology'],
['489', 'https://www.youtube.com/embed/f5otRbpvwtw', 'My Prescription Is...'],
['490', 'https://www.youtube.com/embed/GCpxs3UVnHc', "Don't Tell a Soul"],
['494', 'https://www.youtube.com/embed/IjNICBF-Ock', "Last Night's Dream"] ,
['495', 'https://www.youtube.com/embed/k_K1eEya6y8', "Last Night's Dream"],
['496', 'https://www.youtube.com/embed/PeDGl_ky2XI', "Last Night's Dream"],
['497', 'https://www.youtube.com/embed/lLYrp-p5gs4', "Last Night's Dream"],
['498', 'https://www.youtube.com/embed/tG-RO9gO6mk', "Last Night's Dream"],
['499', 'https://www.youtube.com/embed/jG3LPh5v6ps', "Last Night's Dream"],
['500', 'https://www.youtube.com/embed/y5YB3u1HbYg', "Last Night's Dream"],
['501', 'https://www.youtube.com/embed/EjHuKCD7yJk', "Last Night's Dream"],
['502', 'https://www.youtube.com/embed/ZyswPAQQKHA', "Last Night's Dream"],
['503', 'https://www.youtube.com/embed/jf6JTROKhpo', 'Most Important Words'],
['506', 'https://www.youtube.com/embed/L9GTJdjoY3Q', 'Broadcast Happiness!'],
['507', 'https://www.youtube.com/embed/9NYt3YhQRXw', 'Coming Down To Earth'],
['509', 'https://www.youtube.com/embed/nUVPwqfHoDM', 'Calmer than Normal'],
['512', 'https://www.youtube.com/embed/0rToCpvV1Jc', 'Long-Lived Gods'],
['513', 'https://www.youtube.com/embed/fD1uQC2q4Jo', "Benzaiten's Roots"],
['516', 'https://www.youtube.com/embed/q-KlAz9rXuw', "When I'm Happy"] ,
['517', 'https://www.youtube.com/embed/ZDNf8u9cIaY', "When I'm Happy"],
['518', 'https://www.youtube.com/embed/5yoIfcWaBwk', "When I'm Happy"],
['519', 'https://www.youtube.com/embed/eCuVQmwLiZ0', "When I'm Happy"],
['520', 'https://www.youtube.com/embed/DwuIi0As9EA', "When I'm Happy"],
['521', 'https://www.youtube.com/embed/oYIvtpDOoto', "When I'm Happy"],
['522', 'https://www.youtube.com/embed/GOxtb6gneJ4', "When I'm Happy"],
['523', 'https://www.youtube.com/embed/_Ecv5xZF2pM', 'Castles in the Snow'],
['524', 'https://www.youtube.com/embed/85FuVFynwwo', "When I'm Happy"],
['525', 'https://www.youtube.com/embed/cQDUwJjFakA', "When I'm Happy"],
['531', 'https://www.youtube.com/embed/ZKyVIQwHCWQ', 'Not Just Supporting'],
['533', 'https://www.youtube.com/embed/1n8_v-YVJFs', 'Setsubun Bean Throwing'],
['535', 'https://www.youtube.com/embed/G3x-4pDHiCo', "I Won't Tell Anyone!"],
['536', 'https://www.youtube.com/embed/1y09PqUfThs', 'Not Out Of Duty'],
['537', 'https://www.youtube.com/embed/A-VcUkCe_A4', 'Quite Contrary'],
['540', 'https://www.youtube.com/embed/MQI4NPJwStw', "After School One Day"],
['542', 'https://www.youtube.com/embed/fNZ4jUSHLzk', "Two's Company"],
['545', 'https://www.youtube.com/embed/2tFoBWqC7Bs', 'A Harasho Gift'],
['548', 'https://www.youtube.com/embed/BRXt8PLF91w', 'Bad Habit'],
['551', 'https://www.youtube.com/embed/TB9pZYXAiiA', 'Is This Weird?'],
['555', 'https://www.youtube.com/embed/MFSrlKEHSMo', 'An Unexpected Present'],
['558', 'https://www.youtube.com/embed/P4K3k5hMbic', 'Strange Thoughts'],
['561', 'https://www.youtube.com/embed/3-HVenR4pJc', "Let's Read the News!"],
['562', 'https://www.youtube.com/embed/6VfW8z1TQwI', "Comfort in Company"],
['563', 'https://www.youtube.com/embed/GhLx6qS_T2Q', "Can't You Tell?"],
['564', 'https://www.youtube.com/embed/F_SbtLqIens', 'Racing Genius'],
['567', 'https://www.youtube.com/embed/lXu7bAiYyjQ', 'Tree-Lined Streets'],
['569', 'https://www.youtube.com/embed/bRKXyP0JD6c', 'Party Time!'],
['570', 'https://www.youtube.com/embed/a00ZyTyDmJQ', 'Party Time!'],
['571', 'https://www.youtube.com/embed/7CdTbBflIVA', 'Party Time!'],
['572', 'https://www.youtube.com/embed/0AKn30fDkZw', 'Party Time!'],
['573', 'https://www.youtube.com/embed/XTudFK8Qtps', 'Party Time!'],
['574', 'https://www.youtube.com/embed/7DmEUqRb5X0', 'Party Time!'],
['575', 'https://www.youtube.com/embed/k3ewjFV1N6Q', 'Party Time!'],
['576', 'https://www.youtube.com/embed/YROo9gNj-1g', 'Party Time!'],
['577', 'https://www.youtube.com/embed/LAepdJ8qLGk', 'Party Time!'],
['578', 'https://www.youtube.com/embed/IFHbJf7gzWY', 'Think Again'],
['579', 'https://www.youtube.com/embed/hMC8D2TdRcI', 'Like an Angel'],
['580', 'https://www.youtube.com/embed/D7yaq_AZgaI', "A Bouquet for You"],
['583', 'https://www.youtube.com/embed/kpe78V4Prgg', "Kotori's Egg Hunt"],
['584', 'https://www.youtube.com/embed/9HmliMlOkEQ', 'Try Your Luck'],
['587', 'https://www.youtube.com/embed/FLkjoUMnWzo', "Kotori's Shopping Trip"],
['588', 'https://www.youtube.com/embed/nL0uU1MoB5Y', 'At The Same Speed'],
['595', 'https://www.youtube.com/embed/HVC8duaVNkM', "Maki Nishikino's Survival!"],
['598', 'https://www.youtube.com/embed/msPU1zuBNCk', 'Act Your Age'],
['602', 'https://www.youtube.com/embed/5UonXZZkewk', 'School Idol Detective'],
['604', 'https://www.youtube.com/embed/hXOrOt4BSeo', 'Magician Attempted Hypnotism'],
['606', 'https://www.youtube.com/embed/e-Hr9mfWa84', 'Card Practice!'],
['607', 'https://www.youtube.com/embed/4ktK-7Pg5BE', 'Old Maid Is Tricky'],
['608', 'https://www.youtube.com/embed/TIWIfk441Vk', "Why Can't I Do It?!"],
['619', 'https://www.youtube.com/embed/dLwwjm31rhE', 'Achieve together'],
['620', 'https://www.youtube.com/embed/vcSwjxZC86I', 'Achieve together'],
['621', 'https://www.youtube.com/embed/tJagnxJy3qw', 'Achieve together'],
['622', 'https://www.youtube.com/embed/fu99fHiURdg', 'Achieve together'],
['623', 'https://www.youtube.com/embed/PtHdWlHN_tY', 'Achieve together'],
['624', 'https://www.youtube.com/embed/soPSawEl4Xo', 'Achieve together'],
['625', 'https://www.youtube.com/embed/ggigbnV7pJc', 'Achieve together'],
['626', 'https://www.youtube.com/embed/0gJGoNuncTM', 'Achieve together'],
['627', 'https://www.youtube.com/embed/Qyx8kzQx6xY', 'Achieve together'],
['628', 'https://www.youtube.com/embed/jonmYLwaz7U', 'Nico the Spirit of Joy'],
['629', 'https://www.youtube.com/embed/SnlUZCIrNUQ', 'Alpaca Scene'],
['633', 'https://www.youtube.com/embed/NJGgAmMLTJE', 'Love Spell'],
['634', 'https://www.youtube.com/embed/E_6fHUyFUr8', 'I Might Have Talent'],
['636', 'https://www.youtube.com/embed/Pa5Va0FYPBY', 'Beat Up the Ogres!'],
['639', 'https://www.youtube.com/embed/h6__LdXQKsQ', 'Oceanside Memories'],
['641', 'https://www.youtube.com/embed/cNrRHvfF2wg', 'Forget the Yacht'],
['642', 'https://www.youtube.com/embed/Z4_tZx6Mszs', 'Fanbase Explodes?!'],
['645', 'https://www.youtube.com/embed/_HgY6KaepGE', 'Even Behind a Mask'],
['647', 'https://www.youtube.com/embed/ntmNn5VRmwQ', "I'm Hopeless"],
['648', 'https://www.youtube.com/embed/QwmvS88LUCE', 'Little Honokas?!'],
['650', 'https://www.youtube.com/embed/ktRJ5wsbOIE', 'Hard a Starboard!'],
['652', 'https://www.youtube.com/embed/Iv8RzfeWg2E', 'Meeting a New Me'],
['655', 'https://www.youtube.com/embed/nEnLoRkUJGw', 'I Handle the Hair Care'],
['656', 'https://www.youtube.com/embed/6N_EKdSKyHo', 'My Apologies'],
['658', 'https://www.youtube.com/embed/K8HUTN7hlu0', 'Things Never Change'],
['661', 'https://www.youtube.com/embed/jq-gRVixnVc', 'Too Much TV?'],
['664', 'https://www.youtube.com/embed/NOQm_ml-7j8', 'First Pool Trip'],
['665', 'https://www.youtube.com/embed/WmA_5U02rd8', "The School Pool's Lame"],
['669', 'https://www.youtube.com/embed/0l990K1Z8CE', 'I Love My Routine!'],
['677', 'https://www.youtube.com/embed/pW5biWlF6jg', 'Right Here, Right Now'],
['679', 'https://www.youtube.com/embed/hMMefLwoSok', 'A Different Me'],
['680', 'https://www.youtube.com/embed/ngMOpKM9pRg', 'A Different Me'],
['681', 'https://www.youtube.com/embed/gCKy_2Q9Bcg', 'A Different Me'],
['682', 'https://www.youtube.com/embed/h-DxyVQinfI', 'A Different Me'],
['683', 'https://www.youtube.com/embed/ciVYvGcdDuQ', 'A Different Me'],
['684', 'https://www.youtube.com/embed/WR02WcoQEOA', 'A Different Me'],
['685', 'https://www.youtube.com/embed/ux18CPmxlQ8', 'A Different Me'],
['686', 'https://www.youtube.com/embed/koRQBTE40Oc', 'A Different Me'],
['687', 'https://www.youtube.com/embed/DFefzDzXlWo', 'A Different Me'],
['688', 'https://www.youtube.com/embed/uTqh9SkCCg4', 'Look at Your Fingers!'],
['690', 'https://www.youtube.com/embed/qW0dNy8zaTc', 'Flinging Shurikens'],
['695', 'https://www.youtube.com/embed/7A7AEw2yaSQ', 'Medieval Princesses'],
['697', 'https://www.youtube.com/embed/3G1tQp8Fi84', 'Go See The Elephants'],
['698', 'https://www.youtube.com/embed/DwZrf9ElpJE', 'Bonds With Everyone'],
['699', 'https://www.youtube.com/embed/s3qms0Sp2C0', 'Hamsters Are Idols'],
['700', 'https://www.youtube.com/embed/unAyBOE60os', "Double the Beauty"],
['701', 'https://www.youtube.com/embed/R30AvY6613o', "That's a Secret"],
['703', 'https://www.youtube.com/embed/fHGqDJOPggM', 'Not Like Me'],
['706', 'https://www.youtube.com/embed/kuIrVVT8sdE', "The μ's Zoo!"],
['707', 'https://www.youtube.com/embed/d7iwDPlbfbs', 'From Way Up High'],
['728', 'https://www.youtube.com/embed/DBx3ZrXCa2Y', 'Nico Nico Autumn'],
['732', 'https://www.youtube.com/embed/vzXX2nJCJ-8', 'Princess for a Day'],
['737', 'https://www.youtube.com/embed/YsRIme6m8qg', 'Off to the Jungle!'],
['770', 'https://www.youtube.com/embed/9ggwvOCSLxw', "No Tricks, No Traps"],
['769', 'https://www.youtube.com/embed/89i7wJNYSN4', "Maybe I'll Join Them?"],
['771', 'https://www.youtube.com/embed/T3o7Lxo2Vjo', 'Showtime!'],
['776', 'https://www.youtube.com/embed/HKVFGF8y8_o', 'Stay Focused'],
['778', 'https://www.youtube.com/embed/Ni8OMkDxPIM', 'Fashionable Animals'],
['780', 'https://www.youtube.com/embed/4VWAUtuNL4o', "Our Important Partners"],
['782', 'https://www.youtube.com/embed/8gzElF5UP6o', "Don't Forget to Smile"],
['786', 'https://www.youtube.com/embed/pj-K9jqUPh8', "Greetings"],
['787', 'https://www.youtube.com/embed/FRQxGmd6l_U', "Greetings"],
['788', 'https://www.youtube.com/embed/cBRnE3prL5c', "Greetings"],
['789', 'https://www.youtube.com/embed/Qk2lCAp0tGg', "Greetings"],
['790', 'https://www.youtube.com/embed/_WjAi5R8lZA', "Greetings"],
['791', 'https://www.youtube.com/embed/yMiJwU5x7rA', "Greetings"],
['792', 'https://www.youtube.com/embed/x6E71DklNuc', "Greetings"],
['793', 'https://www.youtube.com/embed/soNOsyopCRc', "Greetings"],
['794', 'https://www.youtube.com/embed/eIK6d2T2s4c', "Greetings"],
['801', 'https://www.youtube.com/embed/mXBZSPPqGI4', "Snowy Memory"],
['802', 'https://www.youtube.com/embed/f7khc_lGztc', "Snowed In"],
['803', 'https://www.youtube.com/embed/pnSYiEZ4lQU', "When I Look at Snow"],
['804', 'https://www.youtube.com/embed/FhZYaL16YhE', "A Show for μ's"],
['805', 'https://www.youtube.com/embed/r05JW9S9_H8', "When It's Snowy!"],
['806', 'https://www.youtube.com/embed/jtdvx7Xoh4c', "All by Myself?!"],
['807', 'https://www.youtube.com/embed/JaBVmrmhRBk', "A Unique Atmosphere?"],
['808', 'https://www.youtube.com/embed/nQ4xa9T67mU', "Speaking of Snow..."],
['809', 'https://www.youtube.com/embed/LsRc_Y6M6ic', "Not Summer, Winter!"],
['821', 'https://www.youtube.com/embed/45gEg1hTpFk', "Representing Now"],
['824', 'https://www.youtube.com/embed/DGfAOm-UeEg', "Sweets Now and Then!"],
['827', 'https://www.youtube.com/embed/BjSTMVi7NuU', "Comparing Uniforms"],
['837', 'https://www.youtube.com/embed/q38_OR9SPng', "A-RISE's Prerogative"],
['838', 'https://www.youtube.com/embed/2ExVaYK2Sbo', "Trusting My Instinct"],
['839', 'https://www.youtube.com/embed/pNb-dTsIyts', "Interview"],
['840', 'https://www.youtube.com/embed/3G4eNd2tumI', "Ideal Woman"],
['842', 'https://www.youtube.com/embed/eoDPedef2Ao', "Monochrome is Fine!"],
['843', 'https://www.youtube.com/embed/-uwbxm7QV_Q', "Time Warp?"],
['894', 'https://www.youtube.com/embed/pwBcCLK5Za8', "You're Cute"],
['895', 'https://www.youtube.com/embed/ArfyzuZ9rvM', "An Empty World"],
['910', 'https://www.youtube.com/embed/gVMq9MS_2gI', "Super Busy!"],
['911', 'https://www.youtube.com/embed/GlDMgFt7gV0', "I'm Nervous"],
['912', 'https://www.youtube.com/embed/0bH5ancfzvw', "No Getting Nervous!"],
['913', 'https://www.youtube.com/embed/0cyJDdp2K3I', "Failure Is Forbidden!"],
['914', 'https://www.youtube.com/embed/jwTkrIuY9TM', "Backstage Report"],
['915', 'https://www.youtube.com/embed/a941l4MDDwU', "Fallen Angel Live"],
['916', 'https://www.youtube.com/embed/mJrA0fbeXSk', "Change My Life"],
['917', 'https://www.youtube.com/embed/1K9_pm9rFbo', "Treasure Preparation"],
['918', 'https://www.youtube.com/embed/2K2jTaCdwxA', "We Did a Show!"],
['919', 'https://www.youtube.com/embed/AlDh1e9h1Po', "Sea Cucumber Debut!"],
['920', 'https://www.youtube.com/embed/RkX1KNxW4pk', "First Contact"],
['921', 'https://www.youtube.com/embed/jQnhfTluKNE', "I Love Dolphins"],
['922', 'https://www.youtube.com/embed/OeUSXgNsbX8', "Only One in the World"],
['923', 'https://www.youtube.com/embed/-RC0XHObEps', "Woman of the Sea!"],
['924', 'https://www.youtube.com/embed/4y0Po99t-hQ', "Yohane's Beauty"],
['925', 'https://www.youtube.com/embed/BbRfNjtKPdU', "Confused Heart"],
['926', 'https://www.youtube.com/embed/6M_bD_1oFug', "Where Do You Stand?"],
['927', 'https://www.youtube.com/embed/_cZka_og8HE', "I Love the Aquarium"],
['959', 'https://www.youtube.com/embed/SPry8mKlNqk', "Wishing's Not Enough"],  
['960', 'https://www.youtube.com/embed/lNXtDsFJSZQ', "My Secret Wish"], 
['1022', 'https://www.youtube.com/embed/LKjGsn-z-ss', 'Shiitake Scene']
];
