var aqours_others_ar = 
[
['Daisuki dattara Daijoubu!',5],
['Kimeta yo Hand in Hand',5],
['Pops heart de Odorun damon!',5],
['Sora mo Kokoro mo Hareru kara',5],
['Waku-Waku-Week!',5],
['Daydream Warrior',5],
['G Senjou no Cinderella',5],
['Thrilling - One Way', 5],
['Awaken the power',5],
['WATER BLUE NEW WORLD',5],
['WONDERFUL STORIES',5],
['Oyasuminasan!',5],
['Pianoforte Monologue',5],
['In this unstable world',5],
['RED GEM WINK',5],
['WHITE FIRST LOVE',5],
['One More Sunshine Story',5],
['Beginner\'s Sailing',5],
['New winding road',5],
['Sakana ka Nanda ka?',5],
['Hajimari Road',5],
['Yosoku Fukanou Driving!',5],
['Marine Border Parasol',5],
];
var aqours_subgroup_ar = 
[
['Strawberry Trapper',4],
['Guilty Night, Guilty Kiss!',4],
['Genki Zenkai DAY! DAY! DAY!',4],
['Yozora wa Nandemo Shitteru no?',4],
['Tokimeki Bunruigaku',4],
['Torikoriko PLEASE',4],
['P.S. no Mukougawa',4],
['Guilty Eyes Fever',4],
['LONELY TUNING',4],
['Kaigandoori de Matteru yo',4],
['Kinmirai Happy End',4],
['INNOCENT BIRD',4],
['GALAXY HidE and SeeK',4],
['Kowareyasuki',4],
['Shadow gate to love',4],
['Guilty!? Farewell party',4],
['Sakura Baibai',4],
['Sotsugyou desu ne',4],
];
var aqours_together = 
[
['Kimi no Kokoro wa Kagayaiteru Kai?',3],
['Step! ZERO to ONE',3],
['Aqours HEROES',3],
['Aozora Jumping Heart',3],
['Koi Ni Naritai AQUARIUM',3],
['Humming Friend',3],
['Mattete Ai no Uta',3],
['Todokanai Hoshi da to Shitemo',3],
['Yume Kataru yori Yume Utaou',3],
['Sunshine Pikkapika Ondo',3],
['Yume de Yozora o Terashitai',3],
['Mijuku DREAMER',3],
['MIRAI TICKET',3],
['Omoi yo Hitotsu ni Nare',3],
['Jingle Bells ga Tomaranai',3],
['Seinaru Hi no Inori',3],
['Taiyou o Oikakero!',3],
['HAPPY PARTY TRAIN',3],
['SKY JOURNEY',3],
['Shoujo Ijou no Koi ga Shitai',3],
['Landing action Yeah!!',3],
['Natsu no Owari no Amaoto ga',3],
['Natsu e no Tobira Never End Ver.',3],
['Manatsu wa Dare no Mono?',3],
['Jimo Ai ♡ Mantan ☆ Summer Life',3],
['Mirai no Bokura Wa Shitteru yo',3],
['Kimi no Hitomi o Meguru Bouken',3],
['Yuuki wa doko ni? Kimi no Mune ni!',3],
['"MY LIST" to you!',3],
['MIRACLE WAVE',3],
['MY Mai☆TONIGHT',3],
['Kiseki Hikaru',3],
['Hop・Step・Waai!',3],
['Thank you, FRIENDS!!',3],
['No.10',3],
['Bokura no Hashittekita Michi wa…',3],
['Next SPARKLING!!',3],
];
var nhs_others_ar = 
[

['Anata no Risou no Heroine',8],
['CHASE!',8],
['Diamond',8],
['Evergreen',8],
['Meccha Going!!',8],
['Nemureru Mori ni Ikitai na',8],
['Starlight',8],
['Yume e no Ippo',8],
['Doki Pipo ☆ Emotion',8],
];
var nhs_subgroup_ar = 
[
];
var nhs_together = 
[
['TOKIMEKI Runners',6],
];
var idol_others_ar = 
[
['Private Wars',9],
['Shocking Party',9],
['SELF CONTROL!!', 9],
['CRASH MIND',9],
['DROPOUT!?',9],
];
