var aqours_others_ar = 
[
['Daisuki dattara Daijoubu!',5],
['Kimeta yo Hand in Hand',5],
['Pops heart de Odorun damon!',5],
['Sora mo Kokoro mo Hareru kara',5],
['Waku-Waku-Week!',5],
['Daydream Warrior',5],
['G Senjou no Cinderella',5],
['Thrilling - One Way', 5],
['Awaken the power',5],
['WATER BLUE NEW WORLD',5],
['WONDERFUL STORIES',5],
['Oyasuminasan!',5],
['Pianoforte Monologue',5],
['In this unstable world',5],
['RED GEM WINK',5],
['WHITE FIRST LOVE',5],
['One More Sunshine Story',5],
['Beginner\'s Sailing',5],
['New winding road',5],
['Sakana ka Nanda ka?',5],
['Hajimari Road',5],
['Yosoku Fukanou Driving!',5],
['Marine Border Parasol',5],
['Kimochi mo Yume mo Issho da ne!',5],
['Misty Frosty Love',5],
['Namida ga Yuki ni Naru Mae ni',5],
['Party! Party! PaPaPaParty!',5],
['Akogare Ranraran',5],
['Cotton Candy Ei-Ei-Oh!',5],
['Love Spiral Tower',5],
['Motto ne!',5],
['Never giving up!',5],
['OKAWARI Happy life!',5],
['Perfect SEKAI',5],
['PURE PHRASE',5],
['Shiny Racers',5],
['Tatehoko Tsubasa',5],
['Totsuzen GIRL',5],
];
