var aqours_others_ar = 
[
['Daisuki dattara Daijoubu!',5],
['Kimeta yo Hand in Hand',5],
['Pops heart de Odorun damon!',5],
['Sora mo Kokoro mo Hareru kara',5],
['Waku-Waku-Week!',5],
['Daydream Warrior',5],
['G Senjou no Cinderella',5],
['Thrilling - One Way', 5],
['Awaken the power',5],
['WATER BLUE NEW WORLD',5],
['WONDERFUL STORIES',5],
['Oyasuminasan!',5],
['Pianoforte Monologue',5],
['In this unstable world',5],
['RED GEM WINK',5],
['WHITE FIRST LOVE',5],
['One More Sunshine Story',5],
['Beginner\'s Sailing',5],
['New winding road',5],
['Sakana ka Nanda ka?',5],
];
