var aqours_subgroup_ar = 
[
['Strawberry Trapper',4],
['Guilty Night, Guilty Kiss!',4],
['Genki Zenkai DAY! DAY! DAY!',4],
['Yozora wa Nandemo Shitteru no?',4],
['Tokimeki Bunruigaku',4],
['Torikoriko PLEASE',4],
['P.S. no Mukougawa',4],
['Guilty Eyes Fever',4],
['LONELY TUNING',4],
['Kaigandoori de Matteru yo',4],
['Kinmirai Happy End',4],
['INNOCENT BIRD',4],
['GALAXY HidE and SeeK',4],
['Kowareyasuki',4],
['Shadow gate to love',4],
['Guilty!? Farewell party',4],
['Sakura Baibai',4],
['Sotsugyou desu ne',4],
['New Romantic Sailors',4],
['Amazing Travel DNA',4],
['Braveheart Coaster',4],
['CHANGELESS',4],
['Kodoku・Teleport',4],
["Kuuchuu Ren'ai Ron",4],
['Love Pulsar',4],
['Maze Sekai',4],
['Phantom Rocket Adventure',4],
['Kodoku Teleport',4],
];
