var aqours_together = 
[
['Kimi no Kokoro wa Kagayaiteru Kai?',3],
['Step! ZERO to ONE',3],
['Aqours HEROES',3],
['Aozora Jumping Heart',3],
['Koi Ni Naritai AQUARIUM',3],
['Humming Friend',3],
['Mattete Ai no Uta',3],
['Todokanai Hoshi da to Shitemo',3],
['Yume Kataru yori Yume Utaou',3],
['Sunshine Pikkapika Ondo',3],
['Yume de Yozora o Terashitai',3],
['Mijuku DREAMER',3],
['MIRAI TICKET',3],
['Omoi yo Hitotsu ni Nare',3],
['Jingle Bells ga Tomaranai',3],
['Seinaru Hi no Inori',3],
['Taiyou o Oikakero!',3],
['HAPPY PARTY TRAIN',3],
['SKY JOURNEY',3],
['Shoujo Ijou no Koi ga Shitai',3],
['Landing action Yeah!!',3],
['Natsu no Owari no Amaoto ga',3],
['Natsu e no Tobira Never',3],
['Manatsu wa Dare no Mono?',3],
['Jimo Ai ♡ Mantan ☆ Summer Life',3],
['Mirai no Bokura Wa Shitteru yo',3],
['Kimi no Hitomi o Meguru Bouken',3],
['Yuuki wa doko ni? Kimi no Mune ni!',3],
['"MY LIST" to you!',3],
['MIRACLE WAVE',3],
['MY Mai☆TONIGHT',3],
['Kiseki Hikaru',3],
['Hop・Step・Waai!',3],
['Thank you, FRIENDS!!',3],
];
