var nhs_others_ar = 
[
['Anata no Risou no Heroine',8],
['CHASE!',8],
['Diamond',8],
['Evergreen',8],
['Meccha Going!!',8],
['Nemureru Mori ni Ikitai na',8],
['Starlight',8],
['Yume e no Ippo',8],
['Doki Pipo ☆ Emotion',8],
['Awakening Promise',8],
['Butterfly',8],
['DIVE!',8],
['Dream with You',8],
['La Bella Patria',8],
['Poppin\' Up!',8],
['Saikou Heart',8],
['Solitude Rain',8],
['Tsunagaru Connect',8],
['VIVID WORLD',8],
];
