var nhs_together = 
[
['TOKIMEKI Runners',6],
['Audrey',6],
['Kaika Sengen',6],
['Koe Tsunagou yo',6],
['Love U my friends',6],
['My Own Fairy-Tale',6],
['Teletelepathy',6],
['Wish',6],
['Yuu & Ai',6],
['☆Wonderland☆',6],
['Aion no Uta',6],
['Aion no Uta',6],
['Analog Heart',6],
['Analog Heart',6],
['Fire Bird',6],
['Fire Bird',6],
['Just Believe!!!',6],
['Just Believe!!!',6],
['Ketsui no Hikari',6],
['Ketsui no Hikari',6],
['LIKE IT! LOVE IT!',6],
['LIKE IT! LOVE IT!',6],
['Margaret',6],
['Margaret',6],
['Mirai Harmony',6],
['Mirai Harmony',6],
['Muteki-kyuu*Believer',6],
['Muteki-kyuu*Believer',6],
['Märchen Star',6],
['Märchen Star',6],
['NEO SKY, NEO MAP!',6],
['NEO SKY, NEO MAP!',6],
['Nijiiro Passions!',6],
['Nijiiro Passions!',6],
['Say Good-Bye Namida',6],
['Say Good-Bye Namida',6],
['Sweet Eyes',6],
['Sweet Eyes',6],
['Tanoshii no Tensai',6],
['Tanoshii no Tensai',6],
['Yagate Hitotsu no Monogatari',6],
['Yagate Hitotsu no Monogatari',6],
['Zensoku Dreamer',6],
['Zensoku Dreamer',6],
];
