var idol_others_ar = 
[
['Private Wars',9],
['Shocking Party',9],
['SELF CONTROL!!', 9],
['CRASH MIND',9],
['DROPOUT!?',9],
['Over The Next Rainbow',9],
['Believe again',9],
['Beautiful Moonlight',9],
['Beautiful Moonlight',9],
['Cheer for you!!',9],
['Cheer for you!!',9],
['Dream Land! Dream World!',9],
['Dream Land! Dream World!',9],
['Love Triangle',9],
['Love Triangle',9],
['Sing & Smile!!',9],
['Sing & Smile!!',9],
['SUPER NOVA',9],
['SUPER NOVA',9],
['Cheer for you!!',9],
['Cheer for you!!',9],
['Dream Land! Dream World!',9],
['Dream Land! Dream World!',9],
['Love Triangle',9],
['Love Triangle',9],
['SUPER NOVA',9],
['SUPER NOVA',9],
];
